### ISSUE TITLE
make tools better

### ISSUE THREAD

**Issue by Constantine-HD** [Gkiokan/ps4-remote-pkg-sender#11]
hi dear 

pleas work on Queue scanner (start next file in the queue after one is finished) ..this is a best option for progtams like this and add delete option for games in queue 
i set update interval to 5sec and request timeout to 3sec but in huge size games . after 5min get error ..program stop working but game continuous to copying

**Comment by Gkiokan** [comment]
The RPI is just unstable on big big big install processes. I guess it just gets an stackoverflow and crashed somewhen. This has been already reported.

Once the Install Process has been started, the RPI is not longer needen for the Install process per se.
But to get updates on the task it have to stay open so we can call him.

I already talked to some scene specific homebrew devs. Updating flatZ RPI is not really a favor they would do for free.
However, I will try to get my hands on, once I have enough time for it. 

Creating awesome tools and bugfixing is plenty of time killer and for now everything is done on my free time.

Next Update is already in progress, I can get you a hipe here. Be patient. I know it's a bit annoying to start all files manually but even then it looks pretty and works very well on all operating systems.

![image](https://user-images.githubusercontent.com/7249224/149634481-9a3dd02a-050b-42b0-9af9-e76adab32514.png)

**Comment by Gkiokan** [comment]
I am already on the Queue and the other big features.  

However if you wanna get hands on the first new touches (hb-store not working correct on install) 
and **the option to remove items from the queue** you may want to try  the [v2.5.0-pre-release](https://github.com/Gkiokan/ps4-remote-pkg-sender/releases/tag/v2.5.0)

**Comment by Constantine-HD** [comment]
I have windows server 2022 and 12tb fpkg
Usually i have 6-7 console to upload fpkg and install games
I add games to server and chose wich one to install in seprate opened program with difrent port and ip then open rpi in seprate console...start to install..evry thing is ok but suddenly rpi get close or rpi in open but connection get error
Now some file stop some one Continues to install
There is no delete option to delete un complite one and add again...
I must start evry thing again

I use to be used the old pkg sender that have torrend link
No error at all .use for 12 console in same time..no error...no bug...fully perfect bud just have one problem 
That have not any queue...install 3 fpk in same time in one console make speed so low..that's why queue so important

Your work is so grate and i respact that ..you do it for free and no one do that ...tanx again for your hard work and we Gratitude

**Comment by Masamune3210** [comment]
try the latest pre-release, it has support for removing single items from the queue

**Comment by Gkiokan** [comment]
@Constantine-HD tbh I had no time this week to release the updates.  
The pre-release version 2.5.0 has the ability to remove items from the queue.  

And also I understand the need of the queue. It will come this week for sure! I am also working on the HB-Store itself.  
I will also add multiple devices support in one of the next next next releases because WAN Install will come, too.  

Yea doing this all on my free time needs huge effort thats why I've added now a ko-fi, so anyone who want can donate and give that a bit more sense.

**Comment by Gkiokan** [comment]
#todo 
- Queue Scanner
- Request Updates optional
- Add rest time

**Comment by abigchopstick** [comment]
why don't I see HB-store tab, nor can I choose PS4 side application? the default one is flatz one and the other is all grey out I cannot choose from?

**Comment by Gkiokan** [comment]
@abigchopstick for the HB-Store Tab (beta) you need the latest released version and **activate it in the Settings first**, because there are still some development to do on pkg-zone.com for having a full implementation. But you will have direct access to the store to download or try to install the pkgs directly (not ready yet).

However the ps4 side applications also are not ready on the latest release because there is no usage for them right now.  
The RPI_OOSDK one haven't been touched since release and the other ones have no benefits yet.  

There will be another Installer support with GoldHEN, soon.  

Currently the development on other projects are on a higher priority.  
While there is less support, this may take a bit time as I am doing it in my free time.  
I put a big Support (buy me a shisha) button that converts my shisha time to code.  

But good news for you guys:
- PKG Reader
- Integrated FTP Client is also in work.

**Comment by Gkiokan** [comment]
Hey guys, let's get hiped a bit. I am done with my unit tests for the queue scanner.  
You can see a proof of concept here on my instagram [queue scanner in action](https://www.instagram.com/p/Cb05rXDj785/). 

So the next realease v2.7.0 will have all this features:  
- [x] Rest Timer
- [x] Queue Scanner (auto install next items)
- [x] HB-Store is fully implemented  
- [x] Better Item Properties and Management for adding and removing them 

Therefore this issue can be closed now as the features are already implemented in the latest release (comming soon).  
However I don't stop yet. I have more crazy ideas that will make this tool #1.
