### ISSUE TITLE
Time out

### ISSUE THREAD

**Issue by Carlito53** [Gkiokan/ps4-remote-pkg-sender#14]
Hi, I'm sure I have configured the server well and I've already tried the recommendation to fix this error, but I always have a time out. However when I click on check ps4 or check server it's good but when I try to install a game I have this time out.
Thank you

**Comment by Gkiokan** [comment]
Please check the [Troubleshooting Guide#timeout](https://github.com/Gkiokan/ps4-remote-pkg-sender/blob/master/Troubleshoot.md#i-get-timeout-error).  

I got recently some reports about that and I guess - as written in the option d and e - this is not an issue with the Tool itself since it appears to happen with the latest GoldHen update.  

I can't debug it currently as I am still on 5.05 but I will take a deeper look into it once the new release is done.

**Comment by Gkiokan** [comment]
This error has been figured out!  

As my assumption was it has something to do with the latest GoldHen2.0b2 update.  
However, you can get around this issue if you use an old GoldHen2.0 payload.  
  
You can find one of the older ones like on nightkinghosts.  Check it. It has been proved already working on the older one.
