### ISSUE TITLE
Fake Timeout Request/PS4 Not available messages

### ISSUE THREAD

**Issue by aquibmastan** [Gkiokan/ps4-remote-pkg-sender#23]
No matter what I send.. somewhere along the transfer I start getting timeouts or PS not available messages. 

Initially, I tried restarting the server, restarting the GUI, restarting PS4, etc but to no avail.

However, I've noticed that as long as RPI is open on the PS4 and I don't mess with the GUI, the transfer actually goes through. I can see the download progressing in the PS4 notifications screen too. Just that this GUI keeps glitching with these fake messages. I have timeout set to max. Using LAN to transfer.

Hoping this gets fixed as it has led to a lot of cancelled (on my part) transfers.

**Comment by Gkiokan** [comment]
You should not leave the RPI on your ps4 because the tool communicates with the RPI on the PS4 only if it is open.  
Sofar, when you jump out of the splash, for whatever reason, it is normal that you get timeout requests because the requests will never answered from the RPI.  

One of the next features will be disable check requests at all. So you can Start the Install and leave the process running without getting updates or trigger the update check manually.   

What do you mean bei GUI keeps glitching? Could you provide a screen cast video?

**Comment by Gkiokan** [comment]
Just as a reminder. In the latest release there is a limit for the error popups. Once they appear, the information interval will be held until you trigger is manually.  Another improvement will be come soon to this with more options. 

Also the Queue Scanner in the next release version will solve the transfer issue a bit as it will handle the package sending automatically.

**Comment by aquibmastan** [comment]
Hi. Sorry for the late reply. Just to clarify my original issue...
If I remain on the RPI screen after initiating the transfer - somewhere down the line, I start getting "Playstation Not available" or Timeout errors on the PackageSender gui. However, actually the package is _being transferred in the background_. Unfortunately, there is no way for me to see the progress and hence I had to come out of the RPI screen to view progress.

I don't have a videocard to capture. Maybe I'll use my phone to take a video next time I transfer. Small files ~1-2GB transfer ok. Large packages (I had mostly over 40GB each) - these were causing this issue.

Just to clarify again - the transfers actually go through fine in the background - just that the packageSender gui on PC keeps showing these errors.
