### ISSUE TITLE
Error 2157510677 | It seems to be installed already

### ISSUE THREAD

**Issue by Waynogeoff** [Gkiokan/ps4-remote-pkg-sender#36]
previously installed and deleted apps and ones that have failed on other install platforms give this error code on trying to send. Status check indicates app already installed even though its not installed or available to load on the PS4. Any way to remove trace on PS4 with your app or maybe FTP?

**Comment by Waynogeoff** [comment]
May have solved it, have to remove any associated notifications on ps4 then try again. Will close when I get a chance to confirm.

**Comment by Gkiokan** [comment]
There are two errors that returns that duplicate content error.  
Sometimes happens when you really have "dead installed pkgs"  
and sometimes this is caused by the notifications that are bind to that specific title id.  
 
After deleting them you should be good. If anything happens, head back on this issue.  

I will have a closer look on that error code on the incoming hotfix update #37

**Comment by ddylard** [comment]
"This is caused by the notifications that are bind to that specific title id. After deleting them you should be good"
 
 This saved me.  adding this hint on the progams pop-up window would be huge as some people like me tend to forget this kind of details...thanks!!
