### ISSUE TITLE
Error -  Task id invalid - 1

### ISSUE THREAD

**Issue by ali-farhad** [Gkiokan/ps4-remote-pkg-sender#51]
I'm running this app on window's 10 same version as in this post. 

I have ps4 pro running on JB 9.00.

I'm connected via LAN cable and homebrew FTP is enabled. 

when I press send file icon,  it's giving me error like "task id invalid".  the value shows up - 1.

ps4 connection and sever connection status gives green no errors.

so what's going on? how do I fix this?

**Comment by Gkiokan** [comment]
Probably an issue with  the RPI (ps4 app). This issue was reported already on the version of backporter [here](https://github.com/Backporter/ps4_remote_pkg_installer-OOSDK/issues/4)

Try to use the RPI [njzydark](https://github.com/njzydark). Go to Mesc -> Downloads ->  dl it. 
Or go directly to his repo, dl it, install it on your ps4 and try again. 

The background of this issue is. The RPI on your ps4 couldn't create a task for the download and therefore it is failing to install anything.  
Solution: Either use legacy RPI from flatZ or the OOP updated one from njzydark [here](https://github.com/njzydark/ps4_remote_pkg_installer-OOSDK/releases)
