### ISSUE TITLE
Unable to set up prerequisites for package 'http://192.168.2.139:8337/

### ISSUE THREAD

**Issue by Kayz0718** [Gkiokan/ps4-remote-pkg-sender#60]
Cant get it to download games. Already tried changing the server port but still nothing

**Comment by Gkiokan** [comment]
This issue was discovered in the early versions of the app. 
There is an Troubleshooting Guide Entry for this, [look here](https://github.com/Gkiokan/ps4-remote-pkg-sender/blob/master/Troubleshoot.md#unable-to-set-up-prerequisites-for-package) which we suggest to swap the ports and restart the server.   
Meanwhile try to restart the RPI on the ps4, too.  

If this doesn't help you try to restart the whole app or try another PKG, just to be sure the PKG is not broken or something.

**Comment by Gkiokan** [comment]
I think the restart has fixed the issue. This has been discussed somewhere on thr repo and we could figure it out with massa.

Usually blocked port or broken pkg or missing header information. Usually restart should work and get all back to working.

Have fun.
