### ISSUE TITLE
Problem when trying to download a game

### ISSUE THREAD

**Issue by arcadan** [Gkiokan/ps4-remote-pkg-sender#62]
It all goes well until it hits 9%, as soon as it reaches 9% it doesnt work anymore. I think, that the first try i did to download it, i somehow fucked up and touched something i shouldnt have and now theres damaged download files on my PS4 and its making it break everytime i retry to download it. The program works fine tho but idk how to fix this specific download, ive already downloaded a lot of other PKGs. 
![asdasdasd](https://github.com/Gkiokan/ps4-remote-pkg-sender/assets/154766288/c2001791-b5fe-4161-9123-1161170796b9)
![adfadfadfadf](https://github.com/Gkiokan/ps4-remote-pkg-sender/assets/154766288/7507ca52-4723-4534-8a95-6db1f07d4c61)

**Comment by Gkiokan** [comment]
On your PS4 go to your Notifciations and delete everything that is for the game. 
Also delete the game once and any other message.  Then start to install it again, and just let it install.   
  
Don't worry about the missing %, this happens on large games because the Installation application on the ps4 (the orange one) wasn't ment to be used that hard, even it works on the latest FW it was build initially for 5.05 a couple years ago.  
  
You could try to use the other PS4 Applications that are on the Misc > Download list as some user said they had better experiences with them.
