### ISSUE TITLE
[win11] non Portable chance to start <10%

### ISSUE THREAD

**Issue by EkkiBrue** [Gkiokan/ps4-remote-pkg-sender#9]
Hi.

I´m having real trouble getting this thing to to start at all. Clicking the icon just sometimes starts server and frontent together and I have a very high chance that one of the windows are not working. To make myself clearer: 

Starting the program sometimes the first screen stays white.
![image](https://user-images.githubusercontent.com/6376844/148593604-50a62f1b-7490-47d2-abfd-dab636663fce.png)

Next time starting up the first screen shows all ok but checking server window shows me another white screen.
![image](https://user-images.githubusercontent.com/6376844/148593674-f6a7fb75-d4cd-486a-a3b0-8c0252078aa3.png)

When everything works both windows show content at the beginning and the sender works a proposed. But most of the time one of both sides do not work...

Win10-x64 on most recent update - using non portable version.

**Comment by Gkiokan** [comment]
It's very strange. Some OS Versions can handle the Storage write throttle correctly but sometimes not.
I'd the chance to test yesterday on a win11 machine of a friend of me. I got randomly not running application, too.

I know whats the error. It's still the Storage race condition caused by multithreading. 
Sometimes it helps if you start it with Administrator privileges but should not be the case.

I know this is annoying. I will go hard on that Storage Library now and try to fix or change it. 
Maybe Instead of crashing the app I just could skip the persistent feature and show a hint message... 

Do you get the trouble on both versions? 

If you are familiar with git, you can clone the repo and run the dev version with `npm i && npm run watch` which will work 100% but is not the optimal flow.
Just in case you wanna get the app working before I fix the issue.

**Comment by EkkiBrue** [comment]
Jepp... Same problem with the portable.
No hassle with the update - if I got it to run it works ;)

Btw. thx for all you effort! Highly appreciated. ;) Hi five from Hansestadt Hamburg ;)

**Comment by Gkiokan** [comment]
@EkkiBrue  Greetings back from munic.   

You guys are really unlucky with win11 and it looks like it is the only Plattform that still made problems.  I am sorry for that.
But I wouldn't be me and myself when I leave that error alive.  

I've digged deeper and deeper in the dependencies and found a way to fix it ultimately.  
The workarround that I've implemented catches now the appearing error and forces the application to create it either way.  
 
I've tested it on win10 and all of my runs have worked. Would be cool if someone could test it on win11, too.  

Here you can go for the [new release v2.4.3](https://github.com/Gkiokan/ps4-remote-pkg-sender/releases/tag/v2.4.3)

Lemme know if everything works for you.

**Comment by EkkiBrue** [comment]
Well - I use Win10x64 ;)
Nevertheless... Will test this out when home again ;)

All the best and thank you!

**Comment by Gkiokan** [comment]
The latest release has been tested by some users now on win10 and win11 and works 100%.
HF with it.
